version: "3"
networks:
  flyserver:
    driver: bridge
services:
  bili_sign:
    image: hyperf/hyperf:8.1-alpine-v3.15-swoole-v5
    container_name: bili_sign
    volumes:
      - ./:/data/projects
    working_dir: /data/projects
    networks:
      - flyserver
    privileged: true
    user: root
    tty: true
    command:
    - /bin/sh
    - -c
    - php bin/hyperf.php bilibili:clock_in
